# Generated by Django 5.0.6 on 2024-06-25 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cirugia',
            fields=[
                ('id_cirugia', models.AutoField(db_column='ID_Cirugia', primary_key=True, serialize=False)),
                ('fecha', models.DateField(db_column='Fecha')),
                ('tipo', models.CharField(db_column='Tipo', max_length=50)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=250, null=True)),
            ],
            options={
                'db_table': 'Cirugia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id_cita', models.AutoField(db_column='ID_Cita', primary_key=True, serialize=False)),
                ('fecha', models.DateField(db_column='Fecha')),
                ('hora', models.TimeField(db_column='Hora')),
                ('motivo', models.CharField(blank=True, db_column='Motivo', max_length=100, null=True)),
            ],
            options={
                'db_table': 'Cita',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id_consulta', models.AutoField(db_column='ID_Consulta', primary_key=True, serialize=False)),
                ('fecha', models.DateField(db_column='Fecha')),
                ('hora', models.TimeField(db_column='Hora')),
                ('diagnostico', models.CharField(blank=True, db_column='Diagnostico', max_length=200, null=True)),
                ('observaciones', models.TextField(blank=True, db_column='Observaciones', null=True)),
            ],
            options={
                'db_table': 'Consulta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dueno',
            fields=[
                ('id_dueno', models.AutoField(db_column='ID_Dueno', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=50)),
                ('apellidos', models.CharField(db_column='Apellidos', max_length=50)),
                ('telefono', models.CharField(blank=True, db_column='Telefono', max_length=20, null=True)),
                ('direccion', models.CharField(blank=True, db_column='Direccion', max_length=100, null=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=50, null=True)),
            ],
            options={
                'db_table': 'Dueno',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id_especialidad', models.AutoField(db_column='ID_Especialidad', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=50)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=200, null=True)),
            ],
            options={
                'db_table': 'Especialidad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Facturacion',
            fields=[
                ('id_factura', models.AutoField(db_column='ID_Factura', primary_key=True, serialize=False)),
                ('fecha', models.DateField(db_column='Fecha')),
                ('total', models.DecimalField(db_column='Total', decimal_places=2, max_digits=10)),
                ('pagado', models.BooleanField(db_column='Pagado', default=False)),
            ],
            options={
                'db_table': 'Facturacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hospitalizacion',
            fields=[
                ('id_hospitalizacion', models.AutoField(db_column='ID_Hospitalizacion', primary_key=True, serialize=False)),
                ('fechaingreso', models.DateField(db_column='FechaIngreso')),
                ('fechaalta', models.DateField(blank=True, db_column='FechaAlta', null=True)),
                ('motivo', models.CharField(blank=True, db_column='Motivo', max_length=200, null=True)),
            ],
            options={
                'db_table': 'Hospitalizacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id_mascota', models.AutoField(db_column='ID_Mascota', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=50)),
                ('raza', models.CharField(blank=True, db_column='Raza', max_length=50, null=True)),
                ('especie', models.CharField(db_column='Especie', max_length=50)),
                ('edad', models.IntegerField(blank=True, db_column='Edad', null=True)),
                ('peso', models.DecimalField(blank=True, db_column='Peso', decimal_places=2, max_digits=5, null=True)),
                ('sexo', models.CharField(blank=True, db_column='Sexo', max_length=1, null=True)),
                ('fechanacimiento', models.DateField(blank=True, db_column='FechaNacimiento', null=True)),
            ],
            options={
                'db_table': 'Mascota',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id_tratamiento', models.AutoField(db_column='ID_Tratamiento', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(db_column='Descripcion', max_length=200)),
                ('dosis', models.CharField(blank=True, db_column='Dosis', max_length=50, null=True)),
                ('duracion', models.CharField(blank=True, db_column='Duracion', max_length=50, null=True)),
                ('fechainicio', models.DateField(blank=True, db_column='FechaInicio', null=True)),
                ('fechafin', models.DateField(blank=True, db_column='FechaFin', null=True)),
            ],
            options={
                'db_table': 'Tratamiento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Veterinario',
            fields=[
                ('id_veterinario', models.AutoField(db_column='ID_Veterinario', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=50)),
                ('apellidos', models.CharField(db_column='Apellidos', max_length=50)),
                ('telefono', models.CharField(blank=True, db_column='Telefono', max_length=20, null=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=50, null=True)),
            ],
            options={
                'db_table': 'Veterinario',
                'managed': False,
            },
        ),
    ]
